// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrhK82CP_quBMykvKqL-K7MRQn_MFId_M',
    appId: '1:310616266750:web:aa6c1771f3807c943892af',
    messagingSenderId: '310616266750',
    projectId: 'at-it-all-task-manager',
    authDomain: 'at-it-all-task-manager.firebaseapp.com',
    storageBucket: 'at-it-all-task-manager.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFX_RL3xFrnBPhOBUp1taTAPQJEZPdxJw',
    appId: '1:310616266750:android:1ca9bcc899a9fcc13892af',
    messagingSenderId: '310616266750',
    projectId: 'at-it-all-task-manager',
    storageBucket: 'at-it-all-task-manager.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKDHoNpynVS5xFb6c_IIzKSv8lmvNAejs',
    appId: '1:310616266750:ios:ef53953faecbeb743892af',
    messagingSenderId: '310616266750',
    projectId: 'at-it-all-task-manager',
    storageBucket: 'at-it-all-task-manager.firebasestorage.app',
    iosBundleId: 'com.example.allAtTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrhK82CP_quBMykvKqL-K7MRQn_MFId_M',
    appId: '1:310616266750:web:a001d4f70de51b993892af',
    messagingSenderId: '310616266750',
    projectId: 'at-it-all-task-manager',
    authDomain: 'at-it-all-task-manager.firebaseapp.com',
    storageBucket: 'at-it-all-task-manager.firebasestorage.app',
  );

}